# by default all the microservice registers to eureka server at 8761
server:
  port: 8761

# since all the microservices register to eureka, we need to disable eureka server to do so
eureka:  client:    fetch-registry: false
    register-with-eureka: false